package com.qgailab.model.po;

import java.util.Date;

public class Award {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.project
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.game
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String game;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.level
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.prize
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String prize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.institution
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String institution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.winner
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String winner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String leader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.id
     *
     * @return the value of award.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.id
     *
     * @param id the value for award.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.number
     *
     * @return the value of award.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Short getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.number
     *
     * @param number the value for award.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setNumber(Short number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.project
     *
     * @return the value of award.project
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.project
     *
     * @param project the value for award.project
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setProject(String project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.game
     *
     * @return the value of award.game
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getGame() {
        return game;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.game
     *
     * @param game the value for award.game
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGame(String game) {
        this.game = game;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.date
     *
     * @return the value of award.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.date
     *
     * @param date the value for award.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.level
     *
     * @return the value of award.level
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.level
     *
     * @param level the value for award.level
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.prize
     *
     * @return the value of award.prize
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getPrize() {
        return prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.prize
     *
     * @param prize the value for award.prize
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setPrize(String prize) {
        this.prize = prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.institution
     *
     * @return the value of award.institution
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.institution
     *
     * @param institution the value for award.institution
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.winner
     *
     * @return the value of award.winner
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getWinner() {
        return winner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.winner
     *
     * @param winner the value for award.winner
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setWinner(String winner) {
        this.winner = winner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.leader
     *
     * @return the value of award.leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.leader
     *
     * @param leader the value for award.leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setLeader(String leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.gmt_create
     *
     * @return the value of award.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.gmt_create
     *
     * @param gmtCreate the value for award.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.gmt_modified
     *
     * @return the value of award.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.gmt_modified
     *
     * @param gmtModified the value for award.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}