package com.qgailab.model.po;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class Award {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.project
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String project;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.game
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String game;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */

    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.level
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.prize
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String prize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.institution
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String institution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.winner
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String winner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String leader;




    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date gmtModified;

}