package com.qgailab.model.po;

import java.util.Date;

public class Copyright {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copyright.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copyright.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copyright.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copyright.rn
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String rn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copyright.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copyright.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column copyright.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copyright.id
     *
     * @return the value of copyright.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copyright.id
     *
     * @param id the value for copyright.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copyright.number
     *
     * @return the value of copyright.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Short getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copyright.number
     *
     * @param number the value for copyright.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setNumber(Short number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copyright.name
     *
     * @return the value of copyright.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copyright.name
     *
     * @param name the value for copyright.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copyright.rn
     *
     * @return the value of copyright.rn
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getRn() {
        return rn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copyright.rn
     *
     * @param rn the value for copyright.rn
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setRn(String rn) {
        this.rn = rn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copyright.date
     *
     * @return the value of copyright.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copyright.date
     *
     * @param date the value for copyright.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copyright.gmt_create
     *
     * @return the value of copyright.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copyright.gmt_create
     *
     * @param gmtCreate the value for copyright.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column copyright.gmt_modified
     *
     * @return the value of copyright.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column copyright.gmt_modified
     *
     * @param gmtModified the value for copyright.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}