package com.qgailab.model.po;

import java.util.Date;

public class Field {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column field.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.id
     *
     * @return the value of field.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.id
     *
     * @param id the value for field.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.uuid
     *
     * @return the value of field.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.uuid
     *
     * @param uuid the value for field.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.name
     *
     * @return the value of field.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.name
     *
     * @param name the value for field.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.gmt_create
     *
     * @return the value of field.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.gmt_create
     *
     * @param gmtCreate the value for field.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.gmt_modified
     *
     * @return the value of field.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.gmt_modified
     *
     * @param gmtModified the value for field.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column field.description
     *
     * @return the value of field.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column field.description
     *
     * @param description the value for field.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}