package com.qgailab.model.po;

import java.util.Date;

public class Honor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column honor.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column honor.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column honor.title
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column honor.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column honor.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column honor.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column honor.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column honor.id
     *
     * @return the value of honor.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column honor.id
     *
     * @param id the value for honor.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column honor.uuid
     *
     * @return the value of honor.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column honor.uuid
     *
     * @param uuid the value for honor.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column honor.title
     *
     * @return the value of honor.title
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column honor.title
     *
     * @param title the value for honor.title
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column honor.date
     *
     * @return the value of honor.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column honor.date
     *
     * @param date the value for honor.date
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column honor.gmt_create
     *
     * @return the value of honor.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column honor.gmt_create
     *
     * @param gmtCreate the value for honor.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column honor.gmt_modified
     *
     * @return the value of honor.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column honor.gmt_modified
     *
     * @param gmtModified the value for honor.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column honor.description
     *
     * @return the value of honor.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column honor.description
     *
     * @param description the value for honor.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}