package com.qgailab.model.po;

import java.util.Date;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.fuuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String fuuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.filename
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.fuuid
     *
     * @return the value of image.fuuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getFuuid() {
        return fuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.fuuid
     *
     * @param fuuid the value for image.fuuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setFuuid(String fuuid) {
        this.fuuid = fuuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.filename
     *
     * @return the value of image.filename
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.filename
     *
     * @param filename the value for image.filename
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.gmt_create
     *
     * @return the value of image.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.gmt_create
     *
     * @param gmtCreate the value for image.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.gmt_modified
     *
     * @return the value of image.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.gmt_modified
     *
     * @param gmtModified the value for image.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}