package com.qgailab.model.po;

import java.util.Date;

public class Leader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader.position
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader.id
     *
     * @return the value of leader.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader.id
     *
     * @param id the value for leader.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader.uuid
     *
     * @return the value of leader.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader.uuid
     *
     * @param uuid the value for leader.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader.name
     *
     * @return the value of leader.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader.name
     *
     * @param name the value for leader.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader.position
     *
     * @return the value of leader.position
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader.position
     *
     * @param position the value for leader.position
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader.gmt_create
     *
     * @return the value of leader.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader.gmt_create
     *
     * @param gmtCreate the value for leader.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader.gmt_modified
     *
     * @return the value of leader.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader.gmt_modified
     *
     * @param gmtModified the value for leader.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader.description
     *
     * @return the value of leader.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader.description
     *
     * @param description the value for leader.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}