package com.qgailab.model.po;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;
@Data
public class Patent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.type
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.zl
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String zl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.inventor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String inventor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date gmtModified;


}