package com.qgailab.model.po;

import java.util.Date;

public class Patent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Short number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.type
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.zl
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String zl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.inventor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String inventor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patent.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.id
     *
     * @return the value of patent.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.id
     *
     * @param id the value for patent.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.number
     *
     * @return the value of patent.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Short getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.number
     *
     * @param number the value for patent.number
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setNumber(Short number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.type
     *
     * @return the value of patent.type
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.type
     *
     * @param type the value for patent.type
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.name
     *
     * @return the value of patent.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.name
     *
     * @param name the value for patent.name
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.zl
     *
     * @return the value of patent.zl
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getZl() {
        return zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.zl
     *
     * @param zl the value for patent.zl
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setZl(String zl) {
        this.zl = zl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.inventor
     *
     * @return the value of patent.inventor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getInventor() {
        return inventor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.inventor
     *
     * @param inventor the value for patent.inventor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setInventor(String inventor) {
        this.inventor = inventor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.gmt_create
     *
     * @return the value of patent.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.gmt_create
     *
     * @param gmtCreate the value for patent.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patent.gmt_modified
     *
     * @return the value of patent.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patent.gmt_modified
     *
     * @param gmtModified the value for patent.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}