package com.qgailab.model.po;

import java.util.Date;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.title
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.uuid
     *
     * @return the value of project.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.uuid
     *
     * @param uuid the value for project.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.title
     *
     * @return the value of project.title
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.title
     *
     * @param title the value for project.title
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gmt_create
     *
     * @return the value of project.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gmt_create
     *
     * @param gmtCreate the value for project.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.gmt_modified
     *
     * @return the value of project.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.gmt_modified
     *
     * @param gmtModified the value for project.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.description
     *
     * @return the value of project.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.description
     *
     * @param description the value for project.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }
}