package com.qgailab.model.po;

import lombok.Data;

import java.util.Date;
import java.util.List;

@Data
public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.uuid
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.title
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String title;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private String description;
    private List<Image> images;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_create
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.gmt_modified
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    private Date gmtModified;




}