package com.qgailab.dao;

import com.qgailab.model.po.Award;
import org.springframework.stereotype.Repository;

@Repository
public interface AwardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insert(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insertSelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    Award selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKeySelective(Award record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table award
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKey(Award record);
}