package com.qgailab.dao;

import com.qgailab.model.po.Award;
import com.qgailab.model.po.Honor;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface HonorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table honor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table honor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insert(Honor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table honor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insertSelective(Honor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table honor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    Honor selectByPrimaryKey(Long id);

    List<Honor> listPage(int page, int pageSize);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table honor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKeySelective(Honor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table honor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Honor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table honor
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKey(Honor record);
}