package com.qgailab.dao;

import com.qgailab.model.po.Intro;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface IntroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intro
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intro
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insert(Intro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intro
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insertSelective(Intro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intro
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    Intro selectByPrimaryKey(Long id);

    List<Intro> listPage();

    int selectCount();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intro
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKeySelective(Intro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intro
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Intro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intro
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKey(Intro record);
}