package com.qgailab.dao;

import com.qgailab.model.po.Award;
import com.qgailab.model.po.Leader;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface LeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insert(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int insertSelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    Leader selectByPrimaryKey(Long id);

    List<Leader> listPage(int page, int pageSize);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKeySelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated Thu Jul 25 21:46:07 CST 2019
     */
    int updateByPrimaryKey(Leader record);
}